# Generated by Django 6.0.7 on 2026-07-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konami', '0003_match_away_corners_match_away_fouls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('postponed', 'Postponed')], default='scheduled', max_length=20),
        ),
    ]
